// alert
export const ALERT_DELETE = 'ALERT_DELETE';
export const ALERT_DATA = 'ALERT_DATA';
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_DELETE_BY_INDEX = 'ALERT_DELETE_BY_INDEX';

// filter
export const TOGGLE_FILTER_WIDGET = 'TOGGLE_FILTER_WIDGET';
export const SAVE_FILTER_DATA_TO_STATE = 'SAVE_FILTER_DATA_TO_STATE';

// currentUser
export const GET_CURRENT_USER_FETCH = 'GET_CURRENT_USER_FETCH';
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';
export const CURRENT_USER_RESET = 'CURRENT_USER_RESET';
