// ieo
export const IEO_LIST_FETCH = 'IEO_LIST_FETCH';
export const IEO_LIST_DATA = 'IEO_LIST_DATA';
export const IEO_LIST_ERROR = 'IEO_LIST_ERROR';

export const IEO_ADD_FETCH = 'IEO_ADD_FETCH';
export const IEO_ADD_DATA = 'IEO_ADD_DATA';
export const IEO_ADD_ERROR = 'IEO_ADD_ERROR';

export const IEO_EDIT_FETCH = 'IEO_EDIT_FETCH';
export const IEO_EDIT_DATA = 'IEO_EDIT_DATA';
export const IEO_EDIT_ERROR = 'IEO_EDIT_ERROR';

export const IEO_GET_FETCH = 'IEO_GET_FETCH';
export const IEO_GET_DATA = 'IEO_GET_DATA';
export const IEO_GET_ERROR = 'IEO_GET_ERROR';

export const IEO_SET_CURRENT_IEO = 'IEO_SET_CURRENT_IEO';
export const IEO_SET_CURRENT_IEO_IFUNSET = 'IEO_SET_CURRENT_IEO_IFUNSET';

export const IEO_HISTORY_FETCH = 'HISTORY_FETCH';
export const IEO_HISTORY_DATA = 'HISTORY_DATA';
export const IEO_HISTORY_ERROR = 'HISTORY_ERROR';
export const IEO_HISTORY_RESET = 'IEO_HISTORY_RESET';

export const UPDATE_IEO_DETAILS_FETCH = 'UPDATE_IEO_DETAILS_FETCH';
export const UPDATE_IEO_DETAILS_DATA = 'UPDATE_IEO_DETAILS_DATA';
export const UPDATE_IEO_DETAILS_ERROR = 'UPDATE_IEO_DETAILS_ERROR';
