// currencies
export const CURRENCIES_LIST_FETCH = 'CURRENCIES_LIST_FETCH';
export const CURRENCIES_LIST_DATA = 'CURRENCIES_LIST_DATA';
export const CURRENCIES_LIST_ERROR = 'CURRENCIES_LIST_ERROR';
export const CURRENCY_ADD_FETCH = 'CURRENCY_ADD_FETCH';
export const CURRENCY_ADD_DATA = 'CURRENCY_ADD_DATA';
export const CURRENCY_ADD_ERROR = 'CURRENCY_ADD_ERROR';
export const CURRENCY_EDIT_FETCH = 'CURRENCY_EDIT_FETCH';
export const CURRENCY_EDIT_DATA = 'CURRENCY_EDIT_DATA';
export const CURRENCY_EDIT_ERROR = 'CURRENCY_EDIT_ERROR';
export const CURRENCY_GET_FETCH = 'CURRENCY_GET_FETCH';
export const CURRENCY_GET_DATA = 'CURRENCY_GET_DATA';
export const CURRENCY_GET_ERROR = 'CURRENCY_GET_ERROR';
